module.exports.descriptors = [
    'Red Water',
    'Blackwater',
    'Diamond',
    'Dusty',
    'Ruby',
    'Open Sky',
    'Zion',
    'Dog Head',
    'New Berlin',
    'Green',
    'Slaughterhouse',
    'Devil Eye',
    'Morning',
    'Grey',
    'Laughing',
    'Hyena',
    'Lion Cub',
    'Bear',
    'Tardigrade',
    'Liberal',
    'Salted',
    'Sideways',
    'Odorous',
    'Haunted',
    'Iron',
    'Velvet',
    'Cancerous',
    'Strawberry'
]

module.exports.places = [
    'Flats',
    'Fields',
    'Village',
    'Canyon',
    'Group Camp',
    'Pond',
    'Horse Camp',
    'Ghost Town',
    'Lake',
    'Camp',
    'Dispersed Camp',
    'Island',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Forest',
    'Cliffs',
    'Hollow',
    'Hunting Camp',
    'Sands',
    'Trail',
    'Trailhead',
    'Tent City',
    'Mountain',
    'Fields'
]